name: Deployment Workflow
on:
    push:
        branches:
            - main
            - 'feature/*'

    workflow_dispatch: 

jobs:
    Docker:
        permissions:
           id-token: write
           contents: read
        runs-on: ubuntu-latest
        name: Docker
        steps:
            - name: Code Checkout
              uses: actions/Checkout@v6    
              
            - name: check directory
              run: pwd && ls  
              
            - name: Build backend image
              run: docker build --tag cat-pomo-backend:v1 ./backend/

            - name: Build frontend image
              run: docker build --tag cat-pomo-frontend:v1 ./frontend/  

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume: ${{vars.AWS_ROLE}}
                aws-region: ap-south-1

            - name: Push to ECR
              id: backend-ecr
              uses: jwalton/gh-ecr-push@v2
              with:
                region: ap-south-1
                image: cat-pomo-backend:v1  

            - name: Push to ECR
              id: frontend-ecr
              uses: jwalton/gh-ecr-push@v2
              with:
                region: ap-south-1
                image: cat-pomo-frontend:v1      
        